### ISSUE TITLE
A UI change

### ISSUE THREAD

**Issue by karanb1** [fluid-project/floeproject.org#100]
## Is your feature request related to a problem?
Dropdowns on the resources page does not have the cursor set to pointer which looks better and creates better user Experience.
## Describe the solution you'd like
Convert the cursor to pointer.

**Comment by jhung** [comment]
@karanb1 
Can you explain why changing the cursor to a pointer will be better for user experience? What is the default browser behaviour for a cursor on a `<button>` element?

**Comment by karanb1** [comment]
It gives the user the feeling that the button is clickable and by hitting the target something will be triggered. The default behaviour of a cursor on the <button> tag is not a hand pointer and this PR tackles that issue.

**Comment by madhatter17** [comment]
> ## Is your feature request related to a problem?
> Dropdowns on the resources page does not have the cursor set to pointer which looks better and creates better user Experience.
> 
> ## Describe the solution you'd like
> Convert the cursor to pointer.

Please assign this issue to me. I am working on it and will solve it soon. Thanks.

**Comment by greatislander** [comment]
Hi, after some consideration we're going to close this issue as the expected cursor for buttons is an arrow. Thanks for the suggestion!
