### ISSUE TITLE
The Images on the home page when hovered did not show any change.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/floeproject.org#103]
## Is your feature request related to a problem?
The images on the home page when hovered did not have any effect.
This effect is not needed for the news pages as the images are too big in size.

## Describe the solution you'd like
The images when hovered should show some change in them like we can decrease the opacity. 
This will make things look better and for a good user experience.

**Comment by jhung** [comment]
@aashimgarg can creating a Github issue, please provide as much detail as possible for us to understand what you are talking about. When you say "images" - which images? All images? Some of them? Just one on a single page? Please be more specific in your details.

Also, why is showing a change to an image when hovered a good user experience? Does it fix usability problem or is it only to make things look "better"? Please explain.

**Comment by aashimgarg** [comment]
@jhung please review it!

**Comment by jobara** [comment]
@aashimgarg you still haven't indicated why changing the images on hover is a good user experience.

**Comment by aashimgarg** [comment]
I think the website will look plain without much effect . Even if there is a small amount of change the website will look better especially the home page.

**Comment by jobara** [comment]
While animations may have some aesthetic appeal, they can be distracting to some, and may not fit with the overall design. For example, by having a hover effect it calls attention to the image. However, in this case the images are not interactive and are more decorative. 

Is there something specific about the images and/or how they are used that you think is causing a problem? Is there something more you are trying to address with the hover effect?

**Comment by aashimgarg** [comment]
@jobara not something much . I just though that images should have aesthetic appeal.

**Comment by greatislander** [comment]
Thanks for the suggestion, but as per @jobara's comment, we won't be making this change.
