### ISSUE TITLE
at text size 1.1 and greater option in "ui option" went down to News make it look like news option.

### ISSUE THREAD

**Issue by Chaitanyassr** [fluid-project/floeproject.org#106]
## Describe the bug
at text size 1.1 and greater option in "ui option" went down to News make it look like news option.

### To reproduce
1.click on preference
2. text size set to 1.1 or greater
3. See error

### Expected behavior
option should be below ui so that it can feel sensible while reading.

## Screenshots
![Screenshot (165)](https://user-images.githubusercontent.com/30374226/75169897-4fbc6100-574f-11ea-962b-506e95e8aa9d.png)

 - Browser [e.g. chrome]

**Comment by shrenikr235** [comment]
This still occurs at sizes greater than 1.2 for different font sizes. Is it still a valid issue?

**Comment by Chaitanyassr** [comment]
> This still occurs at sizes greater than 1.2 for different fonts. Is it still a valid issue?

yes it occurs for 1.1 and greater.

**Comment by sachin10101998** [comment]
@Chaitanyassr , it occurs for text size greater than 1.8 for me. I use latest Chrome and Ubuntu 18.04.

**Comment by jobara** [comment]
@sachin10101998 and @shrenikr235 are you saying that the issue doesn't appear at smaller sizes for you?

**Comment by sachin10101998** [comment]
@jobara , yes.

At text size 1.8:

![Screenshot from 2020-03-03 21-51-32](https://user-images.githubusercontent.com/34926285/75796179-48253980-5d99-11ea-8545-1a85ce6e544c.png)

At text size 1.9:

![Screenshot from 2020-03-03 21-51-44](https://user-images.githubusercontent.com/34926285/75796204-52dfce80-5d99-11ea-8f34-480bfe58afde.png)

**Comment by jobara** [comment]
could everyone please indicate which browsers (including version) and which platform you are testing with.

**Comment by sachin10101998** [comment]
I am using the following:
Browser: Chrome
Version: 80.0.3987.122 (Official Build) (64-bit)
OS: Ubuntu 18.04

**Comment by aashimgarg** [comment]
@jobara at text size 1.7

![Screenshot from 2020-03-04 00-33-52](https://user-images.githubusercontent.com/55639487/75810074-df958700-5daf-11ea-8b2f-208a3653f375.png)

Browser: firefox
OS: Ubuntu 18.04

**Comment by greatislander** [comment]
I'm closing this as we are currently beginning a redesign process which will address this issue alongside other improvements. Thanks for reporting it!
