### ISSUE TITLE
Images are not responsive when the text size is decreased.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/floeproject.org#107]
When the text size is decreased the home page images remains in the same size.
Their size does not decrease.

Screenshot 
![Screenshot from 2020-03-01 01-29-51](https://user-images.githubusercontent.com/55639487/75614172-11aeab00-5b5c-11ea-89c3-52e65988600c.png)

I think the images should be responsive as soon as the text size is decreased the images size should also decrease.

**Comment by sachin10101998** [comment]
@aashimgarg Can you provide more details about this issue? To be precise, which images are you referring to here. It would be really helpful if you could provide screenshots of the same.

**Comment by aashimgarg** [comment]
i am working on this issue!

**Comment by greatislander** [comment]
I'm closing this as we are currently beginning a redesign process which will address this issue along with other improvements. Thanks for reporting it!
