### ISSUE TITLE
The highlighted links overlaps when the line-spacing is decreased.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/floeproject.org#108]
When the line-spacing is decreased the highlighted links (in yellow color) overlaps with the text placed above and beneath it.

Screenshot:-
![Screenshot from 2020-02-29 23-55-24](https://user-images.githubusercontent.com/55639487/75613010-e3769e80-5b4e-11ea-936e-49327cde448b.png)

**Comment by sachin10101998** [comment]
@aashimgarg, please follow the prescribed issue template for submitting issues. Following the template helps to keep track of these issues in the long run when 'obvious things' won't look so evident as the website changes. Not following the requisite template would then make it hard to understand why a particular commit is made in the future. I hope you'd take it as constructive criticism.

**Comment by aashimgarg** [comment]
@sachin10101998, Thanks for your concern. Don't worry I'll do what's necessary.

**Comment by greatislander** [comment]
I'm closing this as we are currently beginning a redesign process which will address this among other improvements. Thanks for reporting it!
