### ISSUE TITLE
Contents of "Table of Contents" overlap with each other when line spacing is less than 1.

### ISSUE THREAD

**Issue by sachin10101998** [fluid-project/floeproject.org#110]
## Describe the bug
Contents of "Table of Contents" overlap with each other when line spacing is less than 1.

### To reproduce
1. Go to Preferences.
2. Turn on the table of contents.
3. Reduce the line spacing to some number less than 0.9

### Expected behavior
The different points in the table of contents should not overlap when line spacing is decreased. 

## Screenshots
![87943276_565176140759600_2311083350351151104_n](https://user-images.githubusercontent.com/34926285/75294190-c770b580-584d-11ea-8b5a-ffdf62e094fb.png)

### Desktop
 - OS: Ubuntu 18.04
 - Browser: Chrome 
 - Version: 80.0.3987.122 (Official Build) (64-bit)

## Additional context or notes
A temporary solution to this problem would be to place a cap on the minimum value of line spacing.

**Comment by sachin10101998** [comment]
@jobara, @jhung, I had a doubt regarding the span of values that different UI options are providing for line spacing. In the [UI Options Demo ](https://build.fluidproject.org/infusion/demos/uiOptions/)and [floe project website](https://floeproject.org/), the line spacing values from 0.7 to 1 cause the list of elements in the table of contents to overlap ( issue described in fluid-project/floeproject.org#110). However, this issue has been solved by placing a cap on line spacing values in [the feedback demo](https://metadata.floeproject.org/demos/feedback/index.html) where it was solved by keeping the values of line spacing between 1 and 2. Does that mean that fluid-project/floeproject.org#110 can be solved by putting a cap on line spacing values so that it's value doesn't go below 1?

**Comment by jobara** [comment]
@sachin10101998 it's probably that they are using different versions of UI Options. The newer versions supports a broader range. That doesn't mean we can't/shouldn't adjust the range for this particular site. I suppose it depends on what is reasonable to support on the site while allowing a user to customize the sites to meet their own needs and preferences.

**Comment by jobara** [comment]
this issue seems related to https://github.com/fluid-project/floeproject.org/issues/108

**Comment by sachin10101998** [comment]
Yes @jobara , both issues can be solved by this:
`.floe-content.floe-story a {
display:inline-block;
}
`

**Comment by greatislander** [comment]
@sachin10101998 We will look at this in the redesign— thanks for reporting!
