### ISSUE TITLE
Image is not alligned properly in mobile.

### ISSUE THREAD

**Issue by Chaitanyassr** [fluid-project/floeproject.org#116]
Image is not alligned properly when viewed in mobile(android device). Image are shifted or align more towards the right side and not the center.
![c2979187-ce2f-4bec-a0ab-808ce88cf66d](https://user-images.githubusercontent.com/30374226/75629193-cd77e500-5c05-11ea-9ca9-4574767a8b77.jpg)

**Comment by jobara** [comment]
@Chaitanyassr please make sure to describe the issue in text, so that those who are not able to perceive the image are able to understand the issue.

**Comment by rishabh1507** [comment]
@jobara @jhung  It is a minor problem that exists in  small devices view .
It occurs because of horizontal scrolling  it can fixed by removing horizonal shifiting while in small screen view

**Comment by greatislander** [comment]
I'm closing this as we are currently beginning a redesign process which will address this among other improvements. Thanks for reporting it!
