### ISSUE TITLE
Adding the social media icons in the footer.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/floeproject.org#117]
## Is your feature request related to a problem?
No this issue is not related to any problem. But by this issue the user can easily come to know more about the floeproject.org and can contribute to it too.
## Describe the solution you'd like
We can add three icons or even more :-
1. Twitter icon :- This will help the user to read the tweets of the the organization.
2. Facebook icon :- This will help the user to go to the facebook page easily .
3. instagram icon :- This will help the user to go to the instagram page easily of the university.

**Comment by aashimgarg** [comment]
@jhung , @jobara should i work on this?

**Comment by jobara** [comment]
@aashimgarg, this is a good suggestion for an updated design, but I'm not sure we are at a point where we can decide exactly where and how these should be represented. Do you have suggestions for the design?

**Comment by aashimgarg** [comment]
@jobara we can add these three icons just at the starting of the footer . I can send this as a pr and then you can see them

**Comment by jobara** [comment]
@jhung thoughts?

**Comment by AbdullahiAbdulkabir** [comment]
It a nice idea

**Comment by Creatoon** [comment]
hello sir , I want to work on this part , should i work?
