### ISSUE TITLE
Show preferences panel bar doesn't fit the small screens.

### ISSUE THREAD

**Issue by thisispratt** [fluid-project/floeproject.org#118]
## The show preferences panel doesn't fit with the screen width.
Show preferences panel does not fit the width of the screen on small scale devices(width < 365px).

### To reproduce
1. Go to  https://floeproject.org
2. Open Chrome dev tools and click on the toggle device toolbar icon.
3. Scroll and set the width less than 365px and then see the error.

### Expected behavior
The show preferences panel div should occupy the 100% width of the device screen.

## 1. iPhone 5/SE (Chrome dev tools simulator)
![image](https://user-images.githubusercontent.com/40731031/75631867-982ac180-5c1c-11ea-8dcc-668d6789b274.png)

## 2.  Samsung galaxy S5 (Chrome dev tools simulator)
![image](https://user-images.githubusercontent.com/40731031/75631894-c6a89c80-5c1c-11ea-8257-56303d686320.png)

## Technical details
This bug is evident because the size of the images doesn't scale down when the width of the device goes small.

**Comment by rishabh1507** [comment]
Hi I have fixed this issue #118  will send a request for it

**Comment by Amulya-coder** [comment]
Hi! I want to fix this issue #118

**Comment by greatislander** [comment]
I'm closing this as we are currently beginning a redesign process which will address this among other improvements. Thanks for reporting it!

**Comment by jhung** [comment]
Fixed in #232
