### ISSUE TITLE
Links overlapping in footer

### ISSUE THREAD

**Issue by sachin10101998** [fluid-project/floeproject.org#121]
## Describe the bug
Links in the footer of website overlap on each other at line spacing values less than 1. 

### To reproduce
1. Go to www.floeproject.org
2. Scroll down to the bottom of the page.

### Expected behavior
Links should not overlap for a better viewing experience. 

## Screenshots
![Screenshot from 2020-03-02 05-17-10](https://user-images.githubusercontent.com/34926285/75636592-0d5ebc80-5c46-11ea-869b-6974c2bea6a2.png)

The problem gets worse when we hover over one of the links.
![Screenshot from 2020-03-02 05-16-57](https://user-images.githubusercontent.com/34926285/75636598-164f8e00-5c46-11ea-959e-fac8922aef95.png)

## Technical details
The display property needs to be fixed.

### Desktop
 - OS: Ubuntu 18.04
 - Browser : Chrome
 - Version: Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by jobara** [comment]
This issue has also been filed at https://issues.fluidproject.org/browse/FLOE-579

**Comment by jobara** [comment]
This issues seems to be related to https://github.com/fluid-project/floeproject.org/issues/108 and https://github.com/fluid-project/floeproject.org/issues/110

**Comment by sachin10101998** [comment]
@jobara, yes, I filed the issue on the issue tracker so as to keep track of it while making commit messages. Having the tag name of the issue helps in linking a particular commit to the description and need of it through the issue tracker.

**Comment by sachin10101998** [comment]
@jobara @jhung 
Solution to #121(this issue) in #122, solves #108 but not #110. 
Solution to #110 can solve #108, but not #121 (this issue).
Solution to #108 as in #122, solves #121(this issue) but not #110.
Hence, even when these issues are similar, they had to be reported separately to maintain order.

**Comment by sachin10101998** [comment]
All the above three issues i.e #121, #110, and #108 can be solved simultaneously by adding the following code to `css/style.css` file : <br>
`
div.columns.large-6.small-12 a {
    display: inline-block;
}
`<br>`
.floe-content.floe-story a {
    display: inline-block;
}
`

**Comment by jobara** [comment]
@sachin10101998 thanks for the explanations. The comments I left above were more house keeping, to link similar issues together for future reference.

However, I'm a bit confused about your previous two comments. It sounds like you are saying the solutions are different in the first comment, but that a single solution can fix all of them, in the latter comment. Or were you trying to specify the difference in how the problem presented itself across the filed issues?

**Comment by sachin10101998** [comment]
@jobara 
Let's say we have three issues A, B, and C, and we have two solutions S1 and S2.  S1 is a single line of code and so is S2. 
S1 individually can solve B and C simultaneously but doesn't solve A. 
S2 individually can solve A and B simultaneously but doesn't solve C. 
Both lines of code (S1 and S2) are to be added in the same file (css/style.css).
Adding them together (S1 and S2) can solve A, B, and C simultaneously. 
The single solution that I was talking about is actually a combination of those two different solutions (S1 and S2). The single solution can solve all three issues simultaneously but those different individual solutions solve only two different issues at a time as explained above.
P.S. 
Here S1 is `div.columns.large-6.small-12 a { display: inline-block; }`
S2 is `.floe-content.floe-story a { display: inline-block; }`
A is #110.
B is #108.
C is #121.

**Comment by greatislander** [comment]
Hi @sachin10101998, thanks for documenting this. We will address it in the forthcoming redesign.

**Comment by jhung** [comment]
Fixed in #232.
