### ISSUE TITLE
Implement a nav toggler icon.

### ISSUE THREAD

**Issue by aashimgarg** [fluid-project/floeproject.org#125]
## Describe the solution you'd like
As we resize the window to a minimum width the toggle icon will contain all the three navbar options.

This will fix the issue #123 in a more efficient way.

**Comment by sachin10101998** [comment]
@aashimgarg the goal of #123 was to make sure that the word 'UI' and 'Options' stay together on resizing. When they split, the 'News' link looks like 'News Options'.
Keeping the navbar items in a single line or not is a design problem unrelated to #123

**Comment by madhatter17** [comment]
> ## Describe the solution you'd like
> As we resize the window to a minimum width the toggle icon will contain all the three navbar options.
> 
> This will fix the issue #123 in a more efficient way.

Please assign this issue to me. I am working on it and will solve in a day or two.

**Comment by aashimgarg** [comment]
Already working on it.

**Comment by greatislander** [comment]
I'm closing this as we are currently beginning a redesign process which will address this among other improvements. Thanks for reporting it!
