### ISSUE TITLE
404 error on network request for tableOFContents-enactor.json (related to infusion)

### ISSUE THREAD

**Issue by sachin10101998** [fluid-project/floeproject.org#131]
## Describe the bug
Console shows 404 for network calls to request data from tableOfContents-enactor.json

### To reproduce
1. Go to www.floeproject.org
2. Right Click anywhere and click on Inspect.
3. Go to Console

### Expected behavior
The error should be removed. 

## Screenshots
![Screenshot from 2020-03-06 05-16-16](https://user-images.githubusercontent.com/34926285/76036446-27600e00-5f6a-11ea-9daf-333e7784593d.png)
![Screenshot from 2020-03-06 05-16-54](https://user-images.githubusercontent.com/34926285/76036448-2a5afe80-5f6a-11ea-95dc-b8eb091fa40b.png)

## Technical details

###Desktop
OS: Ubuntu 18.04
Browser : Chrome
Version: Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by sachin10101998** [comment]
@jobara @jhung 
![Screenshot from 2020-03-06 05-35-35](https://user-images.githubusercontent.com/34926285/76037237-6000e700-5f6c-11ea-973a-d88dd26fa343.png)
These lines are causing this error. Removing them fixes it. Is there any special reason as to why this code is present?

**Comment by jobara** [comment]
@sachin10101998 thanks for filing the issue. 

Rather than providing an image of the code, could you please link directly to that bit of code in the repo. It's hard to see what the context is just from the image. It looks like that code is coming from jQuery, which is a 3rd party dependency of Infusion. If that is the case, you definitely do not want to remove that part of the code. 

When you see a 404 error, you should check to see if the file actually exists and if the path/url is correct.

**Comment by sachin10101998** [comment]
@jobara , the file where these lines are present is quite big so GitHub doesn't show it in its default format and provides the full copy in raw form only. Hence, I couldn't link it directly.  It's on the line number 9603 in [infusion-custom.js](https://github.com/fluid-project/floeproject.org/blob/master/lib/infusion/infusion-custom.js) file. 
>When you see a 404 error, you should check to see if the file actually exists and if the path/url is correct.

I checked for the requisite file and [it's present there](https://github.com/fluid-project/floeproject.org/blob/master/lib/infusion/src/framework/preferences/messages/tableOfContents-enactor.json), but still, it's throwing Error 404.  This is because the file path supplied is wrong. The console is requesting file data from[ this link](https://floeproject.org/framework/preferences/messages/tableOfContents-enactor_en.json?_=1583553670350), but it should request the file from [this link](https://floeproject.org/lib/infusion/src/framework/preferences/messages/tableOfContents-enactor_en.json?_=1583553670350) because that's where the required file lies.
