### ISSUE TITLE
Instead of 2 buttons(expand all and hide all)we can have one single button.

### ISSUE THREAD

**Issue by Chaitanyassr** [fluid-project/floeproject.org#133]
Currently we have 2 different buttons on resources page for show all and hide all. instead of two, we can have one button that will expand every toggle item when state is true and hide the item when state is false in toggleCategory.

We would be changing the name of the buttons as their functionality changes.

page link - https://floeproject.org/resources.html

**Comment by Chaitanyassr** [comment]
@jhung @jobara  can we have this?

**Comment by krishna0303** [comment]
I have solved this issue.

**Comment by greatislander** [comment]
I'm closing this as we are currently beginning a redesign process which will consider this among other improvements. Thanks for reporting it.
