### ISSUE TITLE
Adding smooth collapsed and expand at (https://floeproject.org/resources.html)

### ISSUE THREAD

**Issue by Chaitanyassr** [fluid-project/floeproject.org#134]
We can have smooth collapsed and expand at resources page for expand all,hide all and all the other buttons.
![Screenshot (173)](https://user-images.githubusercontent.com/30374226/76157368-047e5700-612e-11ea-8670-ef407852b099.png)

**Comment by Chaitanyassr** [comment]
@jobara @jhung would it be needed? if yes than i would like to work on it.

**Comment by jobara** [comment]
Could you please explain more about what you mean by smooth collapse and expand?

**Comment by Chaitanyassr** [comment]
currently clicking on learning to learn button displays the content quickly...instead of this can we make it display smoothly by using transition in css or js(infusion)
here is the eg codepen of what i meant by smooth collapse and expand.
https://codepen.io/moudstar/pen/ZKVLPW

**Comment by Chaitanyassr** [comment]
> Could you please explain more about what you mean by smooth collapse and expand?
currently clicking on learning to learn button displays the content quickly...instead of this can we make it display smoothly by using transition in css or js(infusion)
here is the eg codepen of what i meant by smooth collapse and expand.
https://codepen.io/moudstar/pen/ZKVLPW

**Comment by Chaitanyassr** [comment]
> Could you please explain more about what you mean by smooth collapse and expand?

currently clicking on learning to learn button displays the content quickly...instead of this can we make it display smoothly by using transition in css or js(infusion)
here is the eg codepen of what i meant by smooth collapse and expand.
https://codepen.io/moudstar/pen/ZKVLPW

**Comment by jobara** [comment]
@Chaitanyassr thanks for providing the example. We'd have to consider the design. However, with the site potentially changing with the proposed GSoC project. This may be something that should be re-evaluated with that process. @jhung thoughts?

**Comment by Chaitanyassr** [comment]
> @Chaitanyassr thanks for providing the example. We'd have to consider the design. However, with the site potentially changing with the proposed GSoC project. This may be something that should be re-evaluated with that process. @jhung thoughts?

yes, migration to static site generator right? would be submitting  a proposal for it.

**Comment by greatislander** [comment]
I'm closing this as we are currently beginning a redesign process which will explore this alongside other improvements. Thanks for reporting it!
