### ISSUE TITLE
Pointer not visible while viewing the website on a Mobile Phone.

### ISSUE THREAD

**Issue by akhillllldev** [fluid-project/floeproject.org#150]
## Description
Unable to view the right pointer for the contrast preference while viewing it on Google Chrome on a mobile phone.

So basically you have to drag it towards the left, to see the pointer - and I feel like this needs to be fixed :)

## Screenshots
![20200319_162833](https://user-images.githubusercontent.com/40662846/77060888-52813d80-69ff-11ea-9067-cb9f923e990a.jpg)

**Comment by jobara** [comment]
@akhillllldev yes, this is because the whole panel is too wide due to all of the options. We need to figure out way to represent the contrast options in a way that works easier on mobile. In the meantime we've decided to leave it as is and require a bit of horizontal scrolling.
