### ISSUE TITLE
Text size of Hide/Show increases and decreases.

### ISSUE THREAD

**Issue by vaibhav111tandon** [fluid-project/floeproject.org#152]
## Describe the bug
On increasing the text size from the show preferences button, the size of the text also increases/ decreases in `mobile view`

### To reproduce
1. Go to 'mobile website'
2. Click on 'show preferences'
3. Increase the text size

### Expected behavior
Ideally it should not happen.

**Comment by jobara** [comment]
@vaibhav111tandon unfortunately I'm not following what the issue is. The customizations are intended to be applied to both the mobile and desktop presentations. Are they not working? Do you feel that it shouldn't be applied in the mobile view? Is it something else that isn't working?

**Comment by vaibhav111tandon** [comment]
Customization which are applied to the website are changing the view of the preferences tab too...if this is the intended behaviour than this issue can be closed.

**Comment by jobara** [comment]
@vaibhav111tandon thanks for the clarification. Yes that is the intended behaviour.
