### ISSUE TITLE
Add Home link to site navigation

### ISSUE THREAD

**Issue by shash137** [fluid-project/floeproject.org#154]
## Is your feature request related to a problem?
It was getting difficult to switch between the Home page and the other pages of website quickly. Adding the home will make switching easier and landing page will look good.

Below is the screenshot of the current website.
![ss2](https://user-images.githubusercontent.com/44723604/77529290-56a4d380-6eb5-11ea-9ea7-4bb6117dbaaf.PNG)

## How you will resolve the issue?
I would like to add the Home key to the website.
`<li><a href="./index.html">Home</a></li>`

here is the screenshot after changes made.
![ss1](https://user-images.githubusercontent.com/44723604/77529486-b69b7a00-6eb5-11ea-868a-d9f7c84877ae.PNG)

@jhung , @jobara I would like to make changes.

**Comment by shash137** [comment]
#155

**Comment by shash137** [comment]
@jhung, @jobara @colinbdclark I've completed the task and pr is also open, please review it. #155

**Comment by AsaoluElijah** [comment]
Brilliant idea 👌

**Comment by jhung** [comment]
Thank you for the feedback. I have put this on the list of items to review during the new design implementation.

**Comment by kshitij86** [comment]
@jhung @greatislander Has this been added in the site yet? I would like to work on adding this if it hasn't been added yet.

**Comment by greatislander** [comment]
@kshitij86 Thanks for your interest—the new design work is still in progress so we aren't looking for work on this yet.

**Comment by jhung** [comment]
Adding Home to the site navigation is not something we will be doing. Part of the reason is that there are multiple methods to returning Home including the Logo and the breadcrumb.
