### ISSUE TITLE
Index Html margins are off on the left and right

### ISSUE THREAD

**Issue by rishabh1507** [fluid-project/floeproject.org#159]
## Is your feature request related to a problem?
the page cannot fully cover the canvas  the regular margins makes it a little off
## Describe the solution you'd like
The design of this page can be improved if it covers the full page
I see that it is a design of the page but it can be improved if we stretch across the full canvas

##This is just my suggestion  i just want to utilize this blank space may be social media ticker icon bar can be present here. 
![issue](https://user-images.githubusercontent.com/36565299/77828238-3ccaf100-7140-11ea-9ce3-13a077d9733b.JPG)

**Comment by Chaitanyassr** [comment]
> ## Is your feature request related to a problem?
> the page cannot fully cover the canvas the regular margins makes it a little off
> 
> ## Describe the solution you'd like
> The design of this page can be improved if it covers the full page
> I see that it is a design of the page but it can be improved if we stretch across the full canvas
> 
> ##This is just my suggestion i just want to utilize this blank space may be social media ticker icon bar can be present here.
> ![issue](https://user-images.githubusercontent.com/36565299/77828238-3ccaf100-7140-11ea-9ce3-13a077d9733b.JPG)

Can you please provide more details for this issue. Which page are you referring to ?

**Comment by Ayush23Dash** [comment]
@rishabh1507 I believe this is similar to the issue <a href="https://github.com/fluid-project/floeproject.org/issues/118">#118</a>.

**Comment by rishabh1507** [comment]
@Ayush23Dash no not the same

**Comment by rishabh1507** [comment]
@Chaitanyassr  On right side there is a space on which you can have socialmedia-buttons

**Comment by Chaitanyassr** [comment]
> @Chaitanyassr On right side there is a space on which you can have socialmedia-buttons

On which page ? Please provide the details as sometimes image don't load.

**Comment by sachin10101998** [comment]
@rishabh1507 you are proposing a design change which should be discussed with thr community first. Moreover, fluid project is not present on lots of social media platforms either.
Moreover full page is not covered because of explicit sizes of images present on those pages. Changing the max width property solves this issue. A PR for same is already pending.

**Comment by jhung** [comment]
I have put this on the list of things to examine during the new design implementation. Thanks for the feedback.

**Comment by jhung** [comment]
Fixed in #232
