### ISSUE TITLE
Space should be reduced between "flexible learning for open" and "education"

### ISSUE THREAD

**Issue by Chaitanyassr** [fluid-project/floeproject.org#162]
## Describe the bug
Space should be reduced between "flexible learning for open" and "education" as they are the part of the same heading or line.

## Screenshots
![Screenshot (254)](https://user-images.githubusercontent.com/30374226/80393031-905e6500-88cd-11ea-88e6-f17a1ccfeda0.png)

**Comment by Ayush23Dash** [comment]
@Chaitanyassr I think you have increased the font size above 1.2. I am saying this because it is inline till font size=1.2.
Moreover if we go above font size> 1.5 then the ul list of News, Resources. UI Options also gets disoriented.

**Comment by sachin10101998** [comment]
The default preview with default presets in the preferences box doesn't push the 'education' word to the next line. 
![Screenshot from 2020-04-27 22-08-14](https://user-images.githubusercontent.com/34926285/80397485-d0284b00-88d3-11ea-8a48-4e00779dbb6a.png)
