### ISSUE TITLE
Nav Bar should be more clear about pages it serves.

### ISSUE THREAD

**Issue by ShivamSharma-Nsut** [fluid-project/floeproject.org#167]
-> When user click on the any of the NavBar component then that component should be highlighted from rest of the components, for better user experience.
![Screenshot (72)](https://user-images.githubusercontent.com/55797473/85226924-9f5a2300-b3f7-11ea-970f-726f84bffc40.png)
![Screenshot (69)_LI](https://user-images.githubusercontent.com/55797473/85226928-a2edaa00-b3f7-11ea-82b3-a335bc0ebca9.jpg)

**Comment by jhung** [comment]
Thank you for your comment. If I understand correctly what you are reporting is the lack of visual difference for an item that is "currently viewed".

I have added this as a task for upcoming design changes.

**Comment by ShivamSharma-Nsut** [comment]
@jhung So, what type of design you want for the nav bar to close this issue.

**Comment by jhung** [comment]
Addressed in #232
