### ISSUE TITLE
Merge changes from Master into 11ty static site PR #163

### ISSUE THREAD

**Issue by jhung** [fluid-project/floeproject.org#170]
## Is your feature request related to a problem?

The Floe Project master branch has changed since the PR was created and some of the content has changed.

See #169 (https://github.com/fluid-project/floeproject.org/pull/169/files) for all the changes.

## Describe the solution you'd like

The following changes need to be merged into the 11ty Pull Request (#163 )

* Add news Posts:
   * news/2020-07-15-Platform-Co-op-Update.html
   * news/2020-07-14-New-Resources-from-Coding-to-Learn.html
   * news/2020-07-02-WeCountUpdate.html
   * news/2020-06-28-AIHEC-Update.html
   * news/2020-05-20-DEEP-Update.html
   * news/2020-03-27-ODAO-Update.html
* `id=content` added to `<article>` element in the news post template
* Front page `index.html` News list updated

**Comment by jhung** [comment]
@sachin10101998 Thanks!

**Comment by sachin10101998** [comment]
@jhung @BlueSlug @jobara  I have pushed the required changes in the 11ty PR. you can close this issue.
