### ISSUE TITLE
need hyphens in elments of UI OPTIONS in Mobile view

### ISSUE THREAD

**Issue by Raunaksingh100** [fluid-project/floeproject.org#174]
## Describe the bug
the UI OPTIONS need hyphens in mobile view to identify that this is one single word not the two words ,,,,,,,
like ui and options is not a twoword  so add a hyphen in it to identify that this is single word not a two words plz see in the screenshot giiven below for the better understanding.....................

### To reproduce
1. Go to 'http://floeproject.org/'
2. see in the elments on  top 'UI OPTIONS'
3. See error

### Expected behavior
ONLY ADD THE hyphens

## Screenshots
![error floe hphens needs](https://user-images.githubusercontent.com/65535360/89629955-43bafa80-d8bc-11ea-874e-f2e7fe4b1352.PNG)

### Smartphone / tablet 
 - Device: [e.g. galaxy fold]
 - Browser [chrome ]
 - Version [latest]

## Additional context or notes
i already fixed and create a pr for this @jobara @sachin10101998

**Comment by Raunaksingh100** [comment]
i already fixed this issue and create a pr for this 
thanks...........

**Comment by colinbdclark** [comment]
The name "UI Options" is two words, and should not be hyphenated.

**Comment by Raunaksingh100** [comment]
> The name "UI Options" is two words, and should not be hyphenated. 

But need hypens in it because It split into 2 parts ui then options plz see

**Comment by colinbdclark** [comment]
Thanks, but we don't need hyphens here.
