### ISSUE TITLE
text and the  images overlapping in desktop 

### ISSUE THREAD

**Issue by Raunaksingh100** [fluid-project/floeproject.org#178]
## Describe the bug
when we decrease the text -sixe to 0.5 THE TEXT AND THE images are  overlapping with each other in the deskto as well as the mobile view 

### To reproduce
1. Go to 'https://floeproject.org/'
2. do text- size to '0.5'
3. See error

### Expected behavior
images and the text  is not responsive overlaping with each other 

## Screenshot in desktop
![now before now](https://user-images.githubusercontent.com/65535360/89925625-536e7200-dc21-11ea-9e6f-d6767b98af1a.PNG)

### desktop
- - Browser [e.g. stock browser]

## Additional context 
this bug shows in desktop as well as in  mobile

**Comment by Creatoon** [comment]
@jhung @jobara  is this issue taken or can i work on this.

please guide me to reach that bug

**Comment by Raunaksingh100** [comment]
i already create a pr for this @Creatoon  plz find other issues

**Comment by Creatoon** [comment]
OK OK no problem 😀
