### ISSUE TITLE
Update the Floeproject site to the updated design

### ISSUE THREAD

**Issue by jhung** [fluid-project/floeproject.org#183]
The Floeproject site should be updated to include the new design elements as seen in the attached mock-up.

## Waiting on design
- [x] REVIEW Dev site
- [x] feedback to Dev team
- [x] REVIEW High Contrast styling and other UIO settings
- [x] feedback to Dev team
- [x] focus / hover states
- [x] Desktop design page
- [x] home page design (require direction on content)
- [x] resources page
- [x] projects page

## Ready to work on 
- [x] Add notice to the accessibility-sprint-2015 page
- [x] Move security-architecture page to a news article
- [x] Move preference-editing-tools page to a news article
- [x] Copy for projects and etc (need to talk to Michelle and Jon)
- [x] Focus/Hover styling take inspiration from guide site
- [x] #236 - @BlueSlug 
- [x] Fonts across site - @BlueSlug
- [x] News page - @jobara 
- [x] Header -- phase 1 version
- [x] Add SVGs for Creative Commons and etc. (source SVGs with `<use>`) - @BlueSlug
- [x] Integrate styling with UIO (consider using Enactors_base.css and setting styles by manually)
- [x] Mobile Menu - take inspiration from guide site
- [x] style pagination on news page
- [x] General layout styling
- [x] Style news cards
- [x] Style resource cards
- [x] Implement info architecture

## Fonts
**Literata family**
Weights: 400, 500, 600, 700, 800
Styles: roman and italic

**Open Sans**
minimal use in breadcrumbs and prev/next

## mobile visual design
link to Figma: https://www.figma.com/file/G259suL62L7z81p6JYOkxI/FLOE-website-v2?node-id=543%3A73 

<img width="404" alt="Screen Shot 2021-12-02 at 8 33 52 PM" src="https://user-images.githubusercontent.com/11746584/144529814-898fd422-32bc-4c97-8832-36d27197ac2e.png">
<img width="743" alt="Screen Shot 2021-12-02 at 8 33 26 PM" src="https://user-images.githubusercontent.com/11746584/144529816-11e476f1-f834-4891-a015-065b920c4330.png">
<img width="409" alt="Screen Shot 2021-12-02 at 8 33 09 PM" src="https://user-images.githubusercontent.com/11746584/144529817-47470e3d-6f82-49b0-9771-92c8413306f7.png">
<img width="624" alt="Screen Shot 2021-12-02 at 8 32 54 PM" src="https://user-images.githubusercontent.com/11746584/144529819-cf2cc8d4-2abb-41f2-9ad8-1958ce580336.png">
<img width="595" alt="Screen Shot 2021-12-02 at 8 32 39 PM" src="https://user-images.githubusercontent.com/11746584/144529823-d71ba48f-3bf2-4ca0-813a-202cc71b6f28.png">
<img width="645" alt="Screen Shot 2021-12-02 at 9 27 07 PM" src="https://user-images.githubusercontent.com/11746584/144534468-dd30a918-0c67-4b31-83b2-7ece2308a064.png">

![Floe-cards](https://user-images.githubusercontent.com/564762/90532343-1e907c80-e145-11ea-9ce3-aa1e136cfe50.png)

**Comment by greatislander** [comment]
Figma link for reference: https://www.figma.com/file/IFmNnTA84WlQw0noNwsDek/FLOE-website

**Comment by jhung** [comment]
@greatislander: @jobara and I are picking this task up. I was looking at the wireframe and noticed that the "Latest News" cards is a new feature. Do you know of an example of how posts with optional thumbnails would be handled elegantly in 11ty?

**Comment by greatislander** [comment]
[Here's a good example](https://github.com/inclusive-design/wecount.inclusivedesign.ca/blob/dev/src/_includes/components/grid-item.njk) of how this was done for We Count (using [Nunjucks](https://mozilla.github.io/nunjucks/) as the template language).

```njk
	  {% if item.data.picture %}
      <img src="{{ item.data.picture | safe }}" alt="{{ item.data.altTag }}">
      {% else %}
      <svg class="logo placeholder-img">
        <use xlink:href="#placeholder" />
      </svg>
      {% endif %}
```

In this instance there's a fallback SVG image which is used if a given post item doesn't have a thumbnail picture in its data object.

**Comment by carenwatkins** [comment]
SVG of FLOE logo for website can be found on NextCloud: https://files.inclusivedesign.ca/s/ktBow575BNP3pTX #183
