### ISSUE TITLE
Migrate from Foundation to custom CSS and components

### ISSUE THREAD

**Issue by jhung** [fluid-project/floeproject.org#184]
## Is your feature request related to a problem?
The current version of Foundation used for the Floeproject site is old and does not accommodate flexible layouts well (for example see #178).

## Describe the solution you'd like
As part of the work for #183, migrate from Foundation to custom CSS. Perhaps consider using [Pinecone](https://github.com/platform-coop-toolkit/pinecone).

**Comment by greatislander** [comment]
See also: https://issues.fluidproject.org/browse/FLOE-168

**Comment by aryanag1971** [comment]
can I work on this issue?

**Comment by greatislander** [comment]
@aryanag1971 As this project will involve our team working internally to develop a new design and design system for this website, it's not really one that can easily integrate open source contributions. Also, for your information, if your interest in contributing is related to GSOC, we will not be participating in GSOC this year.

**Comment by jhung** [comment]
Fixed in #232
