### ISSUE TITLE
Text and images is overlapping to each other when we reduced text-size

### ISSUE THREAD

**Issue by Raunaksingh100** [fluid-project/floeproject.org#189]
## Describe the bug
when we decrease the text -sixe to 0.5 THE TEXT AND THE images are  overlapping with each other in the desktop,,
Due to the image because image is not responsive .
See in the screenshot which is given below for the better understanding,,
@colinbdclark i made this issue  after the FLOE Website migrated into the static site generator.

### To reproduce
1. Go to 'floeproject website'
2. do text- size to '0.5'
3. Scroll down

### Expected behavior
images and the text  is not responsive overlaping with each other 

## Screenshot in desktop
![now before now](https://user-images.githubusercontent.com/65535360/89925625-536e7200-dc21-11ea-9e6f-d6767b98af1a.PNG)

### desktop
- - Browser [e.g. stock browser]

## Additional context 
this bug shows in desktop

**Comment by greatislander** [comment]
Hi @Raunaksingh100, I'm closing this as we are currently beginning a redesign process which will address this among other improvements. Thanks for reporting it.
