### ISSUE TITLE
Update UI Options page

### ISSUE THREAD

**Issue by greatislander** [fluid-project/floeproject.org#191]
## Is your feature request related to a problem?

Expand on the information provided in the [UI Options](https://floeproject.org/ui-options.html) page of the Floe Website.

## Describe the solution you'd like

Some suggestions:
- first paragraph for non developer
- next paragraph for developer

Say something about UIO not being the start for web accessibility, it’s maybe the second step after having accessible content.

- maybe have an aside to point to web accessibility basics
- maybe link to external blogs like the one from Mike Gifford

## Describe alternative solutions you've considered

Not applicable.

## Additional context or notes

Replaces https://issues.fluidproject.org/browse/FLOE-583.

**Comment by jobara** [comment]
@jhung and @greatislander, can this issue be closed with the current changes to the UI Options page. For example those made by in https://github.com/fluid-project/floeproject.org/commit/a56b4a0e69c4fc0e58af6ce15f682ea661488fed

**Comment by greatislander** [comment]
@jobara If the recent changes fulfill the needs you identified in https://issues.fluidproject.org/browse/FLOE-583 then sure!

**Comment by jhung** [comment]
I'm fine with how the content is currently. This issue can be closed.
