### ISSUE TITLE
Ensure that all HTML passes validation in redesign

### ISSUE THREAD

**Issue by greatislander** [fluid-project/floeproject.org#192]
## Describe the bug

Some HTML does not pass validation.

### To reproduce

N/A.

### Expected behavior

All generated HTML passes validation.

## Additional context or notes

Replaces [FLOE-166](https://issues.fluidproject.org/browse/FLOE-166).

**Comment by Creatoon** [comment]
can i work on this?

**Comment by greatislander** [comment]
@Creatoon thanks for your interest. Our team will be addressing this as part of a larger redesign project.

**Comment by jhung** [comment]
Fixed in #232
