### ISSUE TITLE
Update site with current work

### ISSUE THREAD

**Issue by jobara** [fluid-project/floeproject.org#225]
Update the site content to include the latest work from the past year. 

- Add news article for noteworthy events
- Update front page with references to the [Community-Led Co-design Kit](https://co-design.inclusivedesign.ca) and [Inverted Wordle](https://wecount.inclusivedesign.ca/views/inverted-wordles/)

**Comment by jessmitchell** [comment]
of the links added to the Floe news site, I think these two should be elevated to the front page as reusable resources for FLOE
