### ISSUE TITLE
Create thumbnail project images for Projects section

### ISSUE THREAD

**Issue by jhung** [fluid-project/floeproject.org#239]
## Is your feature request related to a problem?
The Projects section on the Floe site can use some imagery to help break up the text and add some breathing space in content.

## Describe the solution you'd like
Add thumbnail images in NextCloud (https://files.inclusivedesign.ca/s/FeqqWiMLFkCyQLA) for:

- [x] - Community-Led Co-design Kit
- [x] - ILDH
- [x] - We Count
- [x] - Design Guide
- [x] - Weavly
- [x] - UIO
- [x] - Infusion
- [x] - Inclusive Coding Toolkit
- [x] - Open Robot Kit
- [x] - Inverted Wordle
- [x] - Pluralistic Data Infrastructure
- [x] - Hearth
- [x] - Trivet
- [x] - Snow

## Additional context or notes
Reference the Floe redesign figma file for mockup.

Depends on #232

**Comment by jobara** [comment]
Should look at the IDRC site for an example of how images are added to the ideas page. 
https://github.com/inclusive-design/idrc/blob/79142139ffd069b8f8107a4fda3bd5242659e49d/src/_includes/layouts/ideas.njk#L20-L23

It uses a plugin to resize and generate new images from the supplied images.
