### ISSUE TITLE
Add screen reader or other AT details to the Technical Details section

### ISSUE THREAD

**Issue by jhung** [fluid-project/floeproject.org#94]
## Describe the solution you'd like
Add a section to list ATs and their versions in the technical details section of a bug report.

**Comment by bistaastha** [comment]
@jhung Hi! Can I work on adding this to the bug report template?

**Comment by jhung** [comment]
@bistaastha Sure. You can see this template as an example of how it should be done.

https://github.com/fluid-project/fluidproject.org/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by sachin10101998** [comment]
Hey @jhung , Could you elaborate on what 'Technical Details Section' and 'AT details you are referring to here?
